language: python

addons:
  firefox: latest

python:
  - "3.7"

before_install:
  - export GECKODRIVER_VERSION=v0.24.0
  - wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - pytest
